### In this Notebook we are goiing to cover some of the most fudamental concepts of tensor using TensorFLow
More spicifically , we are going to cover
* Introduction to Tensors 
* Getting Information from tensors
* Manipulating Tensors
* Tensor and Numpy
* using @ tf.functions ( a way to speed up your regular python functions)
* Using GPU with Tensor Flow (or TPU)
* Exercises to try for yourself




### Introduction to Tensors

In [ ]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
# creating Tensor with tf.constant()
scalar= tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimension of tensor (ndim stands for number of dimension)
scalar.ndim

0

In [ ]:
# create a vector
vector =tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of vector
vector.ndim

1

In [ ]:
from numpy import mat
# create a Matrix
matrix= tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
# specify the datatype with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we created so far:
* scaler: a single number
* vector: a number with direction  (e.g wind speed and direction)
* Matrix: 2-dimensional array of numbers 
* Tensor: an n-dimensional array of numbers (where n can be any number , a 0-dimensional tensor is a scaler, a 1-dimensional tensor is vector )

### Creating a Tensor with `tf.Variable`

In [ ]:
# Create a same tensor with tf.Variable as above
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Lets try change one of the elements in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Lets try to change our unchangeable Tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

* tf.scaler is fixed Tensor
* tf.variable is changeable Tensor

**Note:**Rarely in practice will you need to decide weather to use **tf.constant** or **tf.variable** to create tensor , as Tensorflow does this for you , if in doubt , use tf.conctant and change it later 

### Creating Random Tensor
Random Tensor are tensors of some arbitrary size that contain random number 

In [ ]:
# create a random(but the same )tensors 
random_1=tf.random.Generator.from_seed(42) #set seed for reproducebility
# we use normal distribution to get the random number
random_1=random_1.normal(shape=(3,2))
# we use normal distribution to get the random number
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
# Are they equal?
random_1, random_2,random_1==random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###  Shuffling the order of Elements in tensors

In [ ]:
# Shuffle a tensor (valuable for you when you want to shuffle your data so the inharent order doesnot effect learning)
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled, not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>, 2)

It looks like if we want our shuffled tensor to be in the same order ,we have to use the globel level random seed as well as the opertaion level random seed :
>Rule 4: "if both globel and operation are set : Both seed are used in conjuction to determine the random sequence

In [ ]:
# shuffle our non-shuffle tensor
tf.random.set_seed(42)  # Globel level random seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make Tensor

In [ ]:
# Create a tensor of all ones 
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy to Tensors
The main difference between Numpy arrays and tensors is that tensors cannot can be run on a GPU (much faster for numerical computing)

In [ ]:
# You can also convert the numpy array to tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32) # create a numpy array between 1 and 25 
numpy_A
# X=tf.constant(some_matrix) # Capital for matrix or tensor
# y=tf.constant(vector) # non-Capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# shape give should satisgy the total number of elements
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
C=tf.constant(numpy_A,shape=(3,8))
A,B,C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [ ]:
2*3*4,3*8

(24, 24)

In [ ]:
A.ndim, B.ndim, C.ndim

(3, 1, 2)

### Getting Information from Tensors

When dealing with tensors you probably to be aware of following attribute :
* Shape
* Rank
* Axsis
* Size


In [ ]:
# Create a rank 4 tensor (4 dimension)
rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5

120

In [ ]:
# Get various attribute of Tensor
print("Datatype of every Element:", rank_4_tensor.dtype)
print("Number of dimension (rank):", rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Element along zero axsis:", rank_4_tensor.shape[0])
print("Elements along last axsis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every Element: <dtype: 'float32'>
Number of dimension (rank): 4
Shape of tensor: (2, 3, 4, 5)
Element along zero axsis: 2
Elements along last axsis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing Tensors
tensor can be indexed like python list

In [ ]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first two element of each tensor 
rank_4_tensor[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
some_list[:1]

[1]

In [ ]:
# Get the first element from each dimension from each index for the final one 
rank_4_tensor[:1,:1,:1]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimension )
rank_2_tensor=tf.constant([[10,7],[3,4]])
rank_2_tensor,rank_2_tensor.ndim, rank_2_tensor.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, 2, TensorShape([2, 2]))

In [ ]:
# Get the last item each rom
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add  extra dimension to our rank 
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=0) # -1 means expand the final axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating Tensors (tensor operations)
**Basic Operation**

`+`,`-`,`*`,`/`



In [ ]:
# You can add values to a tensor using addition operator
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Orignal tensor is unchanged 
# It can be changed by ressignmnet
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# we can use tensorflow build-in  function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

In machine learning , matrix multiplication is one of most common operation

***matrixmultiplication.xyz***

There are two rule our tensors (or matrices) need to fulfil we are going to matrix multiply:
1. The inner dimension must match
2. The resulting matrix has the shape of the outer dimension



In [ ]:
from tensorflow.python.ops.math_ops import matmul
# Matrix Multiplication in tensorflow
print(tensor)
tf,matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


(<module 'tensorflow' from '/usr/local/lib/python3.7/dist-packages/tensorflow/__init__.py'>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [ ]:
tensor,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [ ]:
# Element wise multiplication
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator "@"
tensor@ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# create a tensor of (3,2)
X=tf.constant([[1,2],[3,4],[5,6]])
# create  a tensor of (3,3)
Y=tf.constant([[7,8],[9,10],[11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Try to Matrix Multiply tensor of same shape
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X.shape, tf.reshape(Y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
# Try to Multiply X by reshapes Y
X @ tf.reshape(Y,shape=(2,3))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(X,shape=(2,3)).shape,Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [ ]:
# Try changing the shape of X instead of Y 
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# can do same with transpose
X,tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
# Try matrix multiplication with transpose
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot Product**
Matrix Multiplication is also refered as the dot product

You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# perform the dot product on X and Y (requires X or Y to be Transposed )
tf.tensordot(tf.transpose(X),Y, axes=1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# perform the dot product on X and Y(transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# perform matrix multiplication on X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# check the values of Y, reshape Y and transposed y
print("Normal Y: ",Y,"\n")
print("Y reshaped to (2,3):",tf.reshape(Y,shape=(2,3)),"\n") 
print("Y Transposed:",tf.transpose(Y))

Normal Y:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y Transposed: tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Gernally , when performing matrix multiplication on two tensors and one of the axes donot line up you will transpose rather then reshape one of the tensor to get satisfy multiplication

### Changing the datatype of tensor

In [ ]:
tf.__version__

'2.8.0'

In [ ]:
# Create a datatype with defualt datatype (float32)
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C=tf.constant([7,10])
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [ ]:
# Change from float32 to float16(reduced precesion)
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E=tf.cast(C,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
# float32 to float16
E_float16=tf.cast(E,dtype=tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

### Agregating Tensor
Agregating Tensors =condesing them from multiple values down to smaller amout of values.

In [ ]:
# Getting the absolute value
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following form of aggregation: 
* Get the minimum
* Get the Maximum
* Get the mean of the tensor
* Get the sum of the tensor

In [ ]:
# Create a random tensor with value between 1 and 100 of size 50
E=tf.constant(np.random.randint(1,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([93, 77, 40, 21, 53, 38, 33, 23, 24,  9, 20, 71, 47, 18, 24, 57, 80,
       11, 18, 36, 28, 44, 10, 90, 68, 84, 98, 62,  4,  4, 32,  8, 34, 17,
       81, 68, 96, 66, 66, 72, 85, 58, 94, 52, 34, 40, 51, 80, 51, 93])>

In [ ]:
tf.size(E) , E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
np.min(E)

4

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
np.max(E)

98

In [ ]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
#Find the sum of the tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2463>

In [ ]:
# to find the variance of our tensor , we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E) # won`t work

<tf.Tensor: shape=(), dtype=int64, numpy=796>

In [ ]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.215464>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=796.11237>

### Find the positional Maximum and Minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# fnd the positiona Max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
np.argmax(F)

42

In [ ]:
# index on our largest value position 
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#  Find the maximum value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check the equality 
F[tf.argmax(F)]== tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Sequzing the a tensor (removing all single dimension)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One Hot Encoding Tensors

In [ ]:
# Create a list of indices 
some_list=[0,1,2,3,] # could be red , green , blue ,purple
# one hot encode our list of indices 
tf.one_hot(some_list , depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values for one hot incoding
tf.one_hot(some_list,depth=4,on_value="yo I love deeplearning", off_value="I also like play cricket")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deeplearning', b'I also like play cricket',
        b'I also like play cricket', b'I also like play cricket'],
       [b'I also like play cricket', b'yo I love deeplearning',
        b'I also like play cricket', b'I also like play cricket'],
       [b'I also like play cricket', b'I also like play cricket',
        b'yo I love deeplearning', b'I also like play cricket'],
       [b'I also like play cricket', b'I also like play cricket',
        b'I also like play cricket', b'yo I love deeplearning']],
      dtype=object)>

### Squaring , Log ,square root

In [ ]:
# create a new tensor 
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Find the Square root (Method required non-int type)
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142137, 1.7320509, 2.       , 2.2360682, 2.4494898,
       2.6457515, 2.8284273, 3.0000002], dtype=float32)>

In [ ]:
# Find the Log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor and Numpy
Tensorflow Interact Beautifully with arrays

In [ ]:
# Create a tensor directoly from Numpy
J=tf.constant(np.array([3.,7., 10]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert Tensor back to a Numpy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# The defualt types of each are slightly different
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
# check the data type of each
numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)

### Finding Access to GPU

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Mar  9 10:56:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    58W / 149W |    147MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** if you have access to a CUDA -enabled GPU ,TensorFlow will automatically use it whenever possible 